tasktracker2/lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  def get_current_user(conn, params) do
    user_id = get_session(conn, :user_id)
    if user_id do
       user = Tasktracker.Accounts.get_user!(user_id)
       assign(conn, :current_user, user)
    else
     assign(conn, :current_user, nil)
    end
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    get "/test", PageController, :test
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
    resources "/tasks", TaskController
    get "/tasks/:id/status_task", TaskController, :status_task
    put "tasks/:id/status_task", TaskController, :status_task

  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TasktrackerWeb do
    pipe_through :api
    resources "/time_blocks", BlocksController, except: [:new, :edit]

  end
end

tasktracker2/lib/tasktracker/accounts/user.ex
defmodule Tasktracker.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasktracker.Accounts.User
  alias Tasktracker.Social.Task

  schema "users" do
    field :email, :string
    field :name, :string
    belongs_to :manager, User
    has_many :tasks, Tasktracker.Social.Task
    has_many :users, User, foreign_key: :manager_id
    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:email, :name, :manager_id])
    |> validate_required([:email, :name])
  end
end

tasktracker2/lib/tasktracker_web/controllers/user_controller.ex
defmodule TasktrackerWeb.UserController do
  use TasktrackerWeb, :controller

  import Ecto.Query
  alias Tasktracker.Social
  alias Tasktracker.Social.Task
  alias Tasktracker.Repo
  alias TasktrackerWeb.Router
  alias TasktrackerWeb.SessionController
  alias Tasktracker.Accounts
  alias Tasktracker.Accounts.User
  alias TasktrackerWeb.TaskController
  
  def index(conn, _params) do
   user1 = conn.assigns[:current_user]
   
   if user1.name == "root" do
    users = Accounts.list_users()
   else
    users = Repo.all(from u in Accounts.User, where: u.manager_id == ^user1.id)
 
   end
    render(conn, "index.html", users: users)
   
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    all_users = Accounts.list_users |> Enum.map(&{&1.name, &1.id})
    render(conn, "new.html", changeset: changeset, all_users: all_users)
  end

  def create(conn, %{"user" => user_params}) do
    all_users = Accounts.list_users |> Enum.map(&{&1.name, &1.id})
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, all_users: all_users)
    end
  end

  def show(conn, %{"id" => id}) do
   all_users = Accounts.list_users |> Enum.map(&{&1.name, &1.id})
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user, all_users: all_users)
  end

  def edit(conn, %{"id" => id}) do
    all_users = Accounts.list_users |> Enum.map(&{&1.name, &1.id})
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset, all_users: all_users)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    all_users = Accounts.list_users |> Enum.map(&{&1.name, &1.id})
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset, all_users: all_users)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    num_of_tasks = Repo.all(TasktrackerWeb.TaskController.my_tasks(user)) 
                   |> Enum.count
    IO.inspect(num_of_tasks)
     underlings = Repo.all(from u in Accounts.User, where: u.manager_id == ^user.id) |> Enum.count


    {:ok, _user} =  if num_of_tasks > 0 do
                         conn
                        |> put_flash(:error, "Invalid Action! Assign the Incomplete tasks or mark them complete") 
                        |> redirect(to: user_path(conn, :index))
                    if underlings > 0 do 
   			conn
                        |> put_flash(:error, "Assign underlings to other managers")
                        |> redirect(to: user_path(conn, :index))

                        end
                    else
                        Accounts.delete_user(user)
                        conn
                        |> put_flash(:info, "User deleted successfully.")
                        |> redirect(to: user_path(conn, :index))
                  end
  end
end

tasktracker2/lib/tasktracker_web/views/user_view.ex
defmodule TasktrackerWeb.UserView do
  use TasktrackerWeb, :view
end

tasktracker2/lib/tasktracker_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

tasktracker2/lib/tasktracker_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  

    <div class="form-group">
    Belongs to :
    <%= label f, :manager_id, class: "control-label" %>
    <%= select f, :manager_id, @all_users,  class: "form-control" %>
    <%= error_tag f, :user_id %>
  </div>


  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

tasktracker2/lib/tasktracker_web/templates/user/index.html.eex
<h2>Listing Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th> User Id </th>
      <th> Manager Id </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
<tr>
<td><%= user.email %></td>
<td><%= user.name %></td>
<td><%= user.id %></td>
<td><%= user.manager_id %></td>
<td class="text-right">

<span><%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %></span>
<span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
</td>
</tr>
<% end %>
</tbody>
</table>


<span><%= link "Back", to: task_path(@conn, :index) %></span>

tasktracker2/lib/tasktracker_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: page_path(@conn, :index) %></span>

tasktracker2/lib/tasktracker_web/templates/user/show.html.eex
<h2>Show User</h2>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Manager:</strong>
    <%= @user.manager.name %>
  </li>


</ul>

<span><%= link "Edit", to: user_path(@conn, :edit, @user) %></span> | 
<span><%= link "Back", to: page_path(@conn, :index) %></span> |
<span><%= link "Delete My Account", to: user_path(@conn, :delete, @user), method: :delete, data: [confirm: "Are you sure?"] %></span>